mednax-it/Omniparser_Schemas

hl7v2_default.json

Created the RelatedPerson resource for Guarantor.
If the GT1/guarantor_number is not null, then business identifier will be the guarantor number else mrn+facilityId.

Created the RelatedPerson resource for Guarantor

---

hl7v2_default.json
hl7v2_default_test.json

Reverting changes back for Organization (Payor) resource.

Reverting changes back for Organization (Payor) resource

---

hl7v2_default.json

Added Account resource with mrn-facilityid for business identifier

Added Account resource with mrn-facilityid for business identifier

---

hl7v2_default.json

Added attending practitioner resource to the schema.
Updated Encounter.participant to add the attending practitioner as a reference.
Updated the system url for participant coding to be 'http://terminology.hl7.org/CodeSystem/v3-ParticipationType'.
Renamed a few custom_func's for put/post requests for consistency

Added attending practitioner resource to the schema

---

hl7v2_default.json

1. Added Referring Physician Resource in omniparser schema and update both practitioner attendee and referring conditional request to POST.
2. Validated the FHIR schema generated from Omniparser tool in Smile. No errors.

SMILE-225-Referring Physician Resource

---

hl7v2_default.json

Resolved the guarantor and subscriber gender and dob

Resolved the guarantor and subscriber gender and dob

---

hl7v2_default.json

Added payor name, insurance plan effective date & plan expiration date

Added payor name, insurance plan effective date & plan expiration date

---

.gitignore
hl7v2_default_test.json

Fixed group number value in coverage class.
Changed 
"value": {"xpath": "."},
to:
"value": {"xpath": "IN1/group_number"},

Fixed group number value in coverage class

---

hl7v2_default.json

The hl7v2_default_test.json schema output has been validated in the universal-etl-parser and smilecdr.
Moving hl7v2_default_test to hl7v2_default.

Moving code from hl7v2_default_test to hl7v2_default

---

hl7v2_default.json
hl7v2_default_test.json

SMILECDR-259 Added patient as beneficiary in the Coverage resource

SMILECDR-259 Added patient as beneficiary in the Coverage resource

---

hl7v2_default.json
hl7v2_default_test.json

1. Jason Added Missing Z and IN1
2. Anil validated in Smile

Missing zand in1

---

hl7v2_default_test.json

Added regex to remove special characters after encoding payor identifier

remove special characters after encoding payor identifier

---

hl7v2_default.json
hl7v2_default_test.json

1. PDIP -73 Add Patient Hospital Account # To Bundle
2. PDIP -75 Bundle Populates Resource Elements when Desired Value is not Present
3. PDIP -77 Value provided ('GT1/physical') is not in the value set 'AddressType'
4. PDIP -86 Insurance Work Phone Not Mapped Correctly In Template

Changes for PDIP-73,75,77,86

---

README.md
hl7v2_default.json
hl7v2_default_test.json

1. PDIP-80 - Capture OBR Patient Location in Template 
2. PDIP-81 - Capture OBR Admit Type in Template
3. PDIP-82 - Capture Financial Class in Template
4. PDIP-94 - Capture Patient Type in Template
5. PDIP-96 - Minor Updates to Template (GT1 SSN and Claim Resource)
All validations were completed in Smile with no issues. 
Reference for Test results:
https://mednax1500.atlassian.net/browse/SMILECDR-380
https://mednax1500.atlassian.net/browse/SMILECDR-391

PDIP 80,81,82,94,96

---

hl7v2_default.json
hl7v2_default_test.json

1. Fix transform function syntax for phone type.

Smilecdr 434 fix transform function syntax for phone type

---

hl7v2_default.json
hl7v2_default_test.json

1.  xpath correction for insured address type.

smilecdr 439 xpath correction for IN1 insured address type

---

hl7v2_default.json
hl7v2_default_test.json

SMILECDR-449 'Change-transform-ssn-func-default

SMILECDR-449 'Change-transform-ssn-func-default

---

hl7v2_default.json
hl7v2_default_test.json

1. Modify Claim Identifier Transform Function To Avoid Duplicates Identifiers

SMILECDR-488-Modify-Claim-Identifier-Transform-Function-To-Avoid-Duplicates

---

hl7v2_default.json
hl7v2_default_test.json

Handle Additional NTE and OBX segments

Handle Additional NTE and OBX segments

---

hl7v2_default.json
hl7v2_default_test.json

PDIP-121 Fix duplication when Rend. Doc is Ref. Doc

---

hl7v2_default.json
hl7v2_default_test.json

PDIP-123 Scan EVN and MSH for required message type value

PDIP-123 Scan EVN and MSH for required message type value

---

edi_271.json

https://mednax1500.atlassian.net/browse/MDXCLOUD-6739

Adds service type to template output

---

pmd_to_obr_charges.json

https://mednax1500.atlassian.net/browse/MDXCLOUD-6765

Adds pmd to obr charges schema

---

edi_271.json

[MDXCLOUD-6953](https://mednax1500.atlassian.net/browse/MDXCLOUD-6953)

MDXCLOUD-6953: Update edi_271.json schema to include patient and subscriber address

---

hl7v2_default_test.json

[SMILECDR-1298](https://mednax1500.atlassian.net/browse/SMILECDR-1298)

SMILECDR-1298: Update the condition for maritalStatus object to check for only status of 'm', 's', 'd'

---

hl7v2_default.json

[SMILECDR-1298](https://mednax1500.atlassian.net/browse/SMILECDR-1298)

SMILECDR-1298: Update the condition for the maritalStatus object creation in hl7v2_default schema

---

edi_271.json

https://mednax1500.atlassian.net/browse/MDXCLOUD-7806

MDXCLOUD-7806 - Exposes related entity name
